version: "3.5"
services:
  app:
    build:
      context: .
    restart: always
    privileged: true
    volumes:
      - type: bind
        source: ${DEVICE_PATH_DISPLAY}
        target: "/dev/display"
      - type: bind
        source: ${DEVICE_PATH_CO2_SENSOR}
        target: "/dev/co2"
      - type: bind
        source: ${DEVICE_PATH_TEMP_SENSOR}
        target: "/dev/temp"
    logging:
      options:
        max-size: "200k"
        max-file: "10"
